Feat: Implemented Core ZkEmail Functionality
zkemail/zkemail.rs pull request #1
Opened 2024-11-06 15:29 UTC by shreyas-londhe

# Add DKIM Email Verification and Pattern Matching

Implements core functionality for verifying DKIM-signed emails and extracting patterns using zkVM-compatible regex matching.

## Features
- DKIM signature verification using RSA-SHA256
- Email body hash validation
- Pattern matching using pre-compiled DFAs for zkVM compatibility
- Support for searching in both headers and body
- Optional pattern match revelation

## Implementation Details
- Uses `cfdkim` for email canonicalization
- Implements zkVM-friendly pattern matching using `regex-automata`
- Supports both forward and reverse DFA matching
- Handles UTF-8 encoded content

## Testing
- Verifies DKIM signatures on real email samples
- Tests pattern matching for reset codes and usernames
- Includes test email fixtures

## Usage Example
```rust
let eml_content =
    fs::read("./test_emails/test.eml").context("Failed to read test email")?;
let verifier = EmailVerifier::from_eml(&eml_content).await?;

// Test for reset code
let pattern = r"t7bezzrn"; // The actual reset code from the email
let dfa = DfaRegex::new(pattern)?;
let fwd_bytes = dfa.forward().to_bytes_native_endian().0;
let rev_bytes = dfa.reverse().to_bytes_native_endian().0;

let result = verifier.verify_pattern(
    &fwd_bytes, &rev_bytes, false, // search in body
    true,  // reveal match
)?;

assert!(result.is_some(), "Reset code should be found");
assert_eq!(result.unwrap(), "t7bezzrn", "Should match exact reset code");

// Test for username
let pattern = r"@0xDMello"; // The username from the email
let dfa = DfaRegex::new(pattern)?;
let fwd_bytes = dfa.forward().to_bytes_native_endian().0;
let rev_bytes = dfa.reverse().to_bytes_native_endian().0;

let result = verifier.verify_pattern(
    &fwd_bytes, &rev_bytes, false, // search in body
    true,  // reveal match
)?;

assert!(result.is_some(), "Username should be found");
assert_eq!(result.unwrap(), "@0xDMello", "Should match exact username");
```

2025-01-06 04:07 UTC, Bisht13 requested changes

2025-01-06 04:07 UTC, Bisht13 commented on core/src/utils.rs
> +pub fn process_regex_parts(
regex fns can be in regex.rs instead of utils

2025-01-06 04:07 UTC, Bisht13 commented on core/src/utils.rs
> +        #[cfg(feature = "sp1")]
refactor code to use only 2 attribute (ref code from line 54 to 62)

2025-01-06 04:07 UTC, Bisht13 commented on core/src/utils.rs
> +pub fn verify_dkim(input: &Email, logger: &Logger) -> bool {
shift this to dkim.rs

2025-01-06 04:07 UTC, Bisht13 commented on README.md
>  # ZkEmail.rs
Add required github actions as well

2025-01-06 04:07 UTC, Bisht13 commented on helpers/src/input_generators.rs
> +pub fn read_regex_config(path: &PathBuf) -> Result<RegexConfig> {
Give example of regex config file in readme

2025-01-06 04:07 UTC, Bisht13 commented on helpers/src/input_generators.rs
> +pub fn read_regex_config(path: &PathBuf) -> Result<RegexConfig> {
also this should be same as the decomposed regex we use in zk regex

2025-01-06 04:07 UTC, Bisht13 commented on helpers/src/input_generators.rs
> +fn extract_email_body(email: &mailparse::ParsedMail) -> Result<Vec<u8>> {
https://github.com/zkemail/relayer-utils/blob/cb50b38e9f35d275e19dd8f2cfbe0d0203452c18/src/parse_email.rs#L55Changed Parsed Mail struct to use relayer utils struct as mentioned here

2025-01-06 04:07 UTC, Bisht13 commented on helpers/src/input_generators.rs
> +    debug!("Looking for DKIM signatures...");
If you use https://github.com/zkemail/relayer-utils/blob/cb50b38e9f35d275e19dd8f2cfbe0d0203452c18/src/parse_email.rs#L55, this is already handled

2025-01-06 04:07 UTC, Bisht13 commented on helpers/src/input_generators.rs
> +    debug!("Looking for DKIM signatures...");
dkim resolution wouldn't be needed

2025-01-06 04:38 UTC, shreyas-londhe commented on Cargo.toml
> +rsa = "=0.9.6"
The precompiles are used in the implementations and not here. For example:
risc0 - https://github.com/zkemail/r0-zkEmail/blob/feat/boundless-integration/methods/guest/Cargo.toml#L18
sp1 - https://github.com/zkemail/sp1-zkEmail/blob/main/Cargo.toml#L23

2025-01-06 04:42 UTC, shreyas-londhe commented on core/src/circuits.rs
> +    let parsed_email = parse_mail(&input.email.raw_email).unwrap();
In the circuits, we just need to parse an email to get email properties, and using the default email parser here is fine because we don't need any dns functionalities here. But as you mentioned, we should use the email parser from `relayer-utils` in the script when we are fetching the public key.

2025-01-06 04:45 UTC, shreyas-londhe commented on core/src/utils.rs
> +        #[cfg(feature = "sp1")]
Can you explain it a bit?

2025-01-08 05:26 UTC, shreyas-londhe commented on core/src/structs.rs
> +pub struct EmailVerifierOutput {
We can include this another PR when we are adding email-wallet circuits

2025-01-08 05:28 UTC, shreyas-londhe commented on core/src/circuits.rs
> +    let parsed_email = parse_mail(&input.email.raw_email).unwrap();
I have added the archive to be used when fetching the public key. And it's actually better to use the default cfdkim here for better support.

2025-01-08 05:29 UTC, shreyas-londhe commented on helpers/src/input_generators.rs
> +fn extract_email_body(email: &mailparse::ParsedMail) -> Result<Vec<u8>> {
It's better to use the default mail parser here as it will support maximum number of emails.

2025-01-08 05:29 UTC, shreyas-londhe commented on helpers/src/input_generators.rs
> +    debug!("Looking for DKIM signatures...");
Fetching the key from zkemail archive in the latest commit.

2025-01-08 06:19 UTC, shreyas-londhe commented on core/src/circuits.rs
> +use slog::{o, Discard, Logger};
What is the benefit of the using the relayer-utils logger here? the current logger use-case is not giving any relevant logs anyway.

2025-01-08 07:15 UTC, Bisht13 commented on core/src/circuits.rs
> +use slog::{o, Discard, Logger};
you should log in general in the project and for that we should use our in house logger hence the suggestion, I understand the current logger is just an argument to a function, but apart from it you should use logger to log as well

2025-01-08 07:16 UTC, Bisht13 commented on Cargo.toml
> +rsa = "=0.9.6"
Got it, this rsa crate is used anyway outside circuit right?

2025-01-08 07:18 UTC, Bisht13 commented on core/src/structs.rs
> +pub struct EmailVerifierOutput {
Yea we can do that and instead of timestamp maybe can use hashed header instead, can you create a linear issue to track this?

2025-01-08 07:19 UTC, Bisht13 commented on core/src/circuits.rs
> +    let parsed_email = parse_mail(&input.email.raw_email).unwrap();
I think we should still use our own parsing function so that if in future if we were to make any changes to the parsing logic, it is propagated to all dependencies including this repo

2025-01-08 07:22 UTC, Bisht13 commented on helpers/src/input_generators.rs
> +fn extract_email_body(email: &mailparse::ParsedMail) -> Result<Vec<u8>> {
I don't get maximum number of emails part, aren't we parsing a single email?

2025-01-08 07:58 UTC, shreyas-londhe commented on Cargo.toml
> +rsa = "=0.9.6"
yes

2025-01-08 08:00 UTC, shreyas-londhe commented on core/src/structs.rs
> +pub struct EmailVerifierOutput {
Added.

2025-01-08 08:01 UTC, shreyas-londhe commented on helpers/src/input_generators.rs
> +pub fn read_regex_config(path: &PathBuf) -> Result<RegexConfig> {
Done, will write conversion logic when integrating with backend.

2025-01-08 08:02 UTC, shreyas-londhe commented on helpers/src/input_generators.rs
> +fn extract_email_body(email: &mailparse::ParsedMail) -> Result<Vec<u8>> {
No, I meant the default mail parser library can support a variety of email and handles stuff like QP encoding by itself. So to get maximum compatibility with emails, I decided to use the default library.

2025-01-08 08:24 UTC, shreyas-londhe commented on core/src/circuits.rs
> +    let parsed_email = parse_mail(&input.email.raw_email).unwrap();
I understand this, but the core email parsing logic (decoding email strings into headers/body) will be consistent regardless of implementation. Any custom processing we need can be handled by importing specific functions from our libraries.

Using standard libraries for these fundamental operations is the safer approach - we avoid reinventing the wheel and introducing potential edge case bugs. The standard implementations have been battle-tested.

2025-01-08 08:59 UTC, Bisht13 commented on core/src/circuits.rs
> +    let parsed_email = parse_mail(&input.email.raw_email).unwrap();
We use the same lib inside https://github.com/zkemail/relayer-utils/blob/cb50b38e9f35d275e19dd8f2cfbe0d0203452c18/src/parse_email.rs#L13

2025-01-08 08:59 UTC, Bisht13 commented on helpers/src/input_generators.rs
> +fn extract_email_body(email: &mailparse::ParsedMail) -> Result<Vec<u8>> {
https://github.com/zkemail/zkemail.rs/pull/1#discussion_r1906835078

2025-01-08 09:01 UTC, Bisht13 commented on core/src/structs.rs
> +    pub header_regex_matches: Vec<String>,
@shreyas-londhe

2025-01-08 09:01 UTC, Bisht13 commented on core/src/utils.rs
> +pub fn process_regex_parts(
@shreyas-londhe

2025-01-15 09:00 UTC, merged